import { ArrowRight } from 'lucide-react'
import type { InsightsResponse } from '../api/types'
import { decimal, integer, label, percent } from '../utils/format'

type Props = { data?: InsightsResponse; loading: boolean; error: Error | null; onReviewClick: (ids: string[]) => void }

export default function InsightsView({ data, loading, error, onReviewClick }: Props) {
  if (loading) return <p className="py-16 text-sm text-muted">Loading actionable insights…</p>
  if (error) return <div role="alert" className="panel border-danger p-6 text-danger">Could not load insights: {error.message}</div>
  if (!data) return <div className="panel p-6 text-sm text-muted">Insights are not available yet.</div>
  return <div><div className="grid gap-8 border-b border-ink pb-10 md:grid-cols-[230px_minmax(0,1fr)]"><div><p className="eyebrow">Editorial brief / 01</p><h2 className="section-heading mt-3">Overall summary</h2></div><p className="max-w-4xl font-serif text-[clamp(22px,2.2vw,32px)] leading-snug">{data.overall_summary || 'No overall summary was generated for this sample.'}</p></div>
    <div className="mt-10"><p className="eyebrow">Priority signals / {data.issue_insights.length}</p>{data.issue_insights.length ? data.issue_insights.map((insight, index) => <article key={insight.canonical_id} className="grid gap-7 border-b border-line py-12 md:grid-cols-[100px_minmax(0,1fr)]"><div className="font-mono text-4xl text-orange">{String(index + 1).padStart(2, '0')}</div><div><div className="flex flex-wrap items-center gap-3"><span className="eyebrow">{label(insight.category)}</span><span className="h-1 w-1 rounded-full bg-line" /><span className="eyebrow">Issue insight</span></div><h3 className="mt-3 font-serif text-[clamp(30px,3vw,46px)] leading-tight">{insight.canonical_name ?? 'Unnamed issue'}</h3><div className="mt-6 flex flex-wrap gap-x-8 gap-y-3 border-y border-line py-4 font-mono text-xs tabular"><span><strong className="text-ink">{integer(insight.metrics.review_count)}</strong> reviews</span><span><strong className="text-ink">{percent(insight.metrics.share_of_successful_reviews)}</strong> of sample</span><span>Avg rating <strong className="text-ink">{decimal(insight.metrics.average_rating)}</strong></span><span>1–2★ <strong className="text-ink">{percent(insight.metrics.negative_rating_share)}</strong></span></div><div className="mt-8 grid gap-7 lg:grid-cols-2"><TextBlock title="What users report" text={insight.finding} /><TextBlock title="User impact" text={insight.user_impact} /></div><div className="mt-8 border-t border-line pt-7"><p className="eyebrow">Recommended actions</p><ul className="mt-4 space-y-3">{insight.recommended_actions.map((action, i) => <li key={i} className="grid grid-cols-[24px_1fr] gap-3 text-sm leading-relaxed"><span className="text-orange">→</span><span>{action}</span></li>)}</ul></div>{insight.caveat && <p className="mt-7 border-l-2 border-ochre pl-4 text-xs leading-relaxed text-muted">{insight.caveat}</p>}<div className="mt-7 flex flex-wrap items-center justify-between gap-4"><span className="font-mono text-xs text-muted">Based on {integer(insight.sample_size)} representative {insight.sample_size === 1 ? 'review' : 'reviews'}</span>{insight.supporting_review_ids.length > 0 && <button className="thin-button" onClick={() => onReviewClick(insight.supporting_review_ids)}>View supporting reviews <ArrowRight size={15} /></button>}</div></div></article>) : <p className="border-b border-line py-10 text-sm text-muted">No supported issue insights were generated.</p>}</div>
    {data.feature_request_insights.length > 0 && <section className="mt-16"><div className="border-b border-ink pb-4"><p className="eyebrow">Product opportunities</p><h2 className="section-heading mt-2">Feature request insights</h2></div>{data.feature_request_insights.map((insight, index) => <article key={insight.canonical_id} className="grid gap-6 border-b border-line py-9 md:grid-cols-[100px_minmax(0,1fr)]"><div className="font-mono text-3xl text-orange">{String(index + 1).padStart(2, '0')}</div><div><p className="eyebrow">{label(insight.category)} · {integer(insight.metrics.review_count)} {insight.metrics.review_count === 1 ? 'review' : 'reviews'} · {percent(insight.metrics.share_of_successful_reviews)}</p><h3 className="mt-2 font-serif text-3xl">{insight.canonical_name ?? 'Unnamed request'}</h3><div className="mt-6 grid gap-7 lg:grid-cols-2"><TextBlock title="What users ask for" text={insight.finding} /><TextBlock title="Recommended action" text={insight.recommended_action} /></div>{insight.caveat && <p className="mt-6 border-l-2 border-ochre pl-4 text-xs leading-relaxed text-muted">{insight.caveat}</p>}<div className="mt-6 flex flex-wrap items-center justify-between gap-4"><span className="font-mono text-xs text-muted">Based on {integer(insight.sample_size)} representative {insight.sample_size === 1 ? 'review' : 'reviews'}</span>{insight.supporting_review_ids.length > 0 && <button className="thin-button" onClick={() => onReviewClick(insight.supporting_review_ids)}>View supporting reviews <ArrowRight size={15} /></button>}</div></div></article>)}</section>}
    <section className="mt-16 border-t border-ink pt-5"><p className="eyebrow">Method notes & limitations</p>{data.limitations.length ? <ul className="mt-4 grid gap-3 text-xs leading-relaxed text-muted md:grid-cols-2">{data.limitations.map((item, i) => <li key={i} className="border-l border-line pl-4">{item}</li>)}</ul> : <p className="mt-4 text-sm text-muted">No additional limitations were provided.</p>}</section>
  </div>
}

function TextBlock({ title, text }: { title: string; text: string }) { return <div><p className="eyebrow">{title}</p><p className="mt-3 text-sm leading-relaxed text-ink">{text || 'No detail provided.'}</p></div> }
